// Project45/frontend/app/register/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { UserPlus, User, Mail, Lock, Eye, EyeOff, Info } from 'lucide-react';
import { authApi } from '@/lib/api';
import { useAuthStore } from '@/store/authStore';

export default function RegisterPage() {
  const router = useRouter();
  const { login } = useAuthStore();
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
    confirmPassword: '',
    full_name: '',
  });
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    if (formData.password !== formData.confirmPassword) {
      setError('两次输入的密码不一致');
      setLoading(false);
      return;
    }

    if (formData.password.length < 6) {
      setError('密码长度至少6位');
      setLoading(false);
      return;
    }

    try {
      const registerRes = await authApi.register({
        username: formData.username,
        email: formData.email,
        password: formData.password,
        full_name: formData.full_name,
      });

      const loginRes = await authApi.login({
        username: formData.username,
        password: formData.password,
      });

      login(loginRes.data.access_token, loginRes.data.user);
      router.push('/');
    } catch (err: any) {
      setError(err.response?.data?.detail || '注册失败，请稍后重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-heritage-paper to-white flex items-center justify-center py-12 px-4">
      <div className="max-w-md w-full">
        <div className="text-center mb-8">
          <Link href="/" className="inline-flex items-center space-x-2 mb-6">
            <div className="w-16 h-16 bg-gradient-to-br from-heritage-red to-heritage-gold rounded-2xl flex items-center justify-center">
              <span className="text-white font-bold text-3xl">遗</span>
            </div>
          </Link>
          <h1 className="text-3xl font-bold text-heritage-ink mb-2 font-serif">
            创建账号
          </h1>
          <p className="text-gray-600">加入我们，开启非遗文化传承之旅</p>
        </div>

        <div className="bg-white rounded-2xl shadow-lg p-8">
          <form onSubmit={handleSubmit} className="space-y-5">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                用户名 <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <User className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type="text"
                  value={formData.username}
                  onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                  placeholder="请输入用户名"
                  className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-heritage-gold focus:border-transparent outline-none transition-all"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                邮箱 <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="请输入邮箱地址"
                  className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-heritage-gold focus:border-transparent outline-none transition-all"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                姓名
              </label>
              <div className="relative">
                <User className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type="text"
                  value={formData.full_name}
                  onChange={(e) => setFormData({ ...formData, full_name: e.target.value })}
                  placeholder="请输入您的真实姓名（选填）"
                  className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-heritage-gold focus:border-transparent outline-none transition-all"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                密码 <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  placeholder="请输入密码（至少6位）"
                  className="w-full pl-12 pr-12 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-heritage-gold focus:border-transparent outline-none transition-all"
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                </button>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                确认密码 <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={formData.confirmPassword}
                  onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                  placeholder="请再次输入密码"
                  className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-heritage-gold focus:border-transparent outline-none transition-all"
                  required
                />
              </div>
            </div>

            {error && (
              <div className="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-xl text-sm">
                {error}
              </div>
            )}

            <div className="flex items-start space-x-2 text-sm text-gray-500">
              <Info size={16} className="flex-shrink-0 mt-0.5 text-heritage-gold" />
              <p>注册即表示您同意我们的服务条款和隐私政策，我们将保护您的个人信息安全。</p>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full btn-primary py-4 text-lg font-bold flex items-center justify-center space-x-2 disabled:opacity-50"
            >
              <UserPlus size={20} />
              <span>{loading ? '注册中...' : '注册账号'}</span>
            </button>
          </form>

          <div className="mt-6 text-center">
            <p className="text-gray-600">
              已有账号？
              <Link href="/login" className="text-heritage-red hover:text-red-600 font-medium ml-1">
                立即登录
              </Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// Project46/client/src/pages/Register.tsx
import { createSignal } from 'solid-js';
import { useNavigate, A } from '@solidjs/router';
import { authStore } from '../store/authStore';
import { socketService } from '../services/socket';

export default function Register() {
  const navigate = useNavigate();
  const [username, setUsername] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [nickname, setNickname] = createSignal('');
  const [error, setError] = createSignal('');
  const [loading, setLoading] = createSignal(false);

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!username() || !password() || !nickname()) {
      setError('请填写完整信息');
      return;
    }
    if (password().length < 6) {
      setError('密码至少6位');
      return;
    }

    setLoading(true);
    setError('');

    try {
      await authStore.register(username(), password(), nickname());
      socketService.init();
      navigate('/');
    } catch (e: any) {
      setError(e.message || '注册失败');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={{
      width: '100%',
      height: '100%',
      display: 'flex',
      'align-items': 'center',
      'justify-content': 'center',
      background: 'linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)',
    }}>
      <div class="fade-in" style={{
        width: '400px',
        padding: '40px',
        background: 'rgba(30, 41, 59, 0.9)',
        'border-radius': '16px',
        'backdrop-filter': 'blur(10px)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        'box-shadow': '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
      }}>
        <div style={{ 'text-align': 'center', 'margin-bottom': '32px' }}>
          <h1 style={{
            'font-size': '32px',
            'margin-bottom': '8px',
            background: 'linear-gradient(90deg, #60a5fa, #a78bfa)',
            '-webkit-background-clip': 'text',
            '-webkit-text-fill-color': 'transparent',
          }}>创建账号</h1>
          <p style={{ color: '#94a3b8', 'font-size': '14px' }}>加入元宇宙办公系统</p>
        </div>

        <form onSubmit={handleSubmit}>
          {error() && (
            <div style={{
              padding: '12px',
              background: 'rgba(239, 68, 68, 0.1)',
              border: '1px solid rgba(239, 68, 68, 0.3)',
              color: '#fca5a5',
              'border-radius': '8px',
              'margin-bottom': '16px',
              'font-size': '14px',
            }}>{error()}</div>
          )}

          <div style={{ 'margin-bottom': '16px' }}>
            <label style={{ display: 'block', 'margin-bottom': '8px', 'font-size': '14px', color: '#cbd5e1' }}>用户名</label>
            <input
              type="text"
              value={username()}
              onInput={(e) => setUsername(e.target.value)}
              placeholder="至少3个字符"
              style={{
                width: '100%',
                padding: '12px 16px',
                background: 'rgba(15, 23, 42, 0.8)',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                'border-radius': '8px',
                color: '#e2e8f0',
                'font-size': '14px',
              }}
            />
          </div>

          <div style={{ 'margin-bottom': '16px' }}>
            <label style={{ display: 'block', 'margin-bottom': '8px', 'font-size': '14px', color: '#cbd5e1' }}>昵称</label>
            <input
              type="text"
              value={nickname()}
              onInput={(e) => setNickname(e.target.value)}
              placeholder="请输入您的昵称"
              style={{
                width: '100%',
                padding: '12px 16px',
                background: 'rgba(15, 23, 42, 0.8)',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                'border-radius': '8px',
                color: '#e2e8f0',
                'font-size': '14px',
              }}
            />
          </div>

          <div style={{ 'margin-bottom': '24px' }}>
            <label style={{ display: 'block', 'margin-bottom': '8px', 'font-size': '14px', color: '#cbd5e1' }}>密码</label>
            <input
              type="password"
              value={password()}
              onInput={(e) => setPassword(e.target.value)}
              placeholder="至少6个字符"
              style={{
                width: '100%',
                padding: '12px 16px',
                background: 'rgba(15, 23, 42, 0.8)',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                'border-radius': '8px',
                color: '#e2e8f0',
                'font-size': '14px',
              }}
            />
          </div>

          <button
            type="submit"
            disabled={loading()}
            style={{
              width: '100%',
              padding: '12px',
              background: 'linear-gradient(90deg, #3b82f6, #8b5cf6)',
              color: 'white',
              border: 'none',
              'border-radius': '8px',
              'font-size': '16px',
              'font-weight': '600',
              cursor: loading() ? 'not-allowed' : 'pointer',
              opacity: loading() ? 0.7 : 1,
              transition: 'all 0.2s',
            }}
          >
            {loading() ? '注册中...' : '注册'}
          </button>
        </form>

        <div style={{ 'text-align': 'center', 'margin-top': '20px' }}>
          <span style={{ color: '#94a3b8', 'font-size': '14px' }}>已有账号？</span>
          <A href="/login" style={{ color: '#60a5fa', 'margin-left': '8px', 'text-decoration': 'none' }}>立即登录</A>
        </div>
      </div>
    </div>
  );
}
