// Project45/frontend/app/login/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { LogIn, User, Mail, Lock, Eye, EyeOff } from 'lucide-react';
import { authApi } from '@/lib/api';
import { useAuthStore } from '@/store/authStore';

export default function LoginPage() {
  const router = useRouter();
  const { login } = useAuthStore();
  const [formData, setFormData] = useState({
    username: '',
    password: '',
  });
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const res = await authApi.login(formData);
      login(res.data.access_token, res.data.user);
      router.push('/');
    } catch (err: any) {
      setError(err.response?.data?.detail || '登录失败，请检查用户名和密码');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-heritage-paper to-white flex items-center justify-center py-12 px-4">
      <div className="max-w-md w-full">
        <div className="text-center mb-8">
          <Link href="/" className="inline-flex items-center space-x-2 mb-6">
            <div className="w-16 h-16 bg-gradient-to-br from-heritage-red to-heritage-gold rounded-2xl flex items-center justify-center">
              <span className="text-white font-bold text-3xl">遗</span>
            </div>
          </Link>
          <h1 className="text-3xl font-bold text-heritage-ink mb-2 font-serif">
            欢迎回来
          </h1>
          <p className="text-gray-600">登录您的账号，开始非遗学习之旅</p>
        </div>

        <div className="bg-white rounded-2xl shadow-lg p-8">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                用户名
              </label>
              <div className="relative">
                <User className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type="text"
                  value={formData.username}
                  onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                  placeholder="请输入用户名"
                  className="w-full pl-12 pr-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-heritage-gold focus:border-transparent outline-none transition-all"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                密码
              </label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  placeholder="请输入密码"
                  className="w-full pl-12 pr-12 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-heritage-gold focus:border-transparent outline-none transition-all"
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                </button>
              </div>
            </div>

            {error && (
              <div className="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-xl text-sm">
                {error}
              </div>
            )}

            <button
              type="submit"
              disabled={loading}
              className="w-full btn-primary py-4 text-lg font-bold flex items-center justify-center space-x-2 disabled:opacity-50"
            >
              <LogIn size={20} />
              <span>{loading ? '登录中...' : '登录'}</span>
            </button>
          </form>

          <div className="mt-6 p-4 bg-heritage-paper rounded-xl">
            <p className="text-sm text-gray-600 mb-2 font-medium">演示账号：</p>
            <div className="space-y-1 text-sm text-gray-500">
              <p>管理员：admin / admin123</p>
              <p>讲师：master_zhang / 123456</p>
              <p>学员：learner_wang / 123456</p>
            </div>
          </div>

          <div className="mt-6 text-center">
            <p className="text-gray-600">
              还没有账号？
              <Link href="/register" className="text-heritage-red hover:text-red-600 font-medium ml-1">
                立即注册
              </Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// Project48/frontend/src/views/login/index.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useUserStore } from '@/stores/user'
import { Cpu, Lock, User, Eye, EyeOff } from 'lucide-vue-next'
import type { FormInstance, FormRules } from 'element-plus'

const router = useRouter()
const route = useRoute()
const userStore = useUserStore()

const formRef = ref<FormInstance>()
const loading = ref(false)
const showPassword = ref(false)

const loginForm = reactive({
  username: '',
  password: ''
})

const rules: FormRules = {
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
    { min: 2, max: 20, message: '用户名长度在 2 到 20 个字符', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 6, max: 32, message: '密码长度在 6 到 32 个字符', trigger: 'blur' }
  ]
}

async function handleLogin() {
  if (!formRef.value) return
  
  await formRef.value.validate(async (valid) => {
    if (valid) {
      loading.value = true
      try {
        await userStore.login(loginForm.username, loginForm.password)
        const redirect = route.query.redirect as string || '/dashboard'
        router.push(redirect)
      } catch (error) {
        console.error('登录失败:', error)
      } finally {
        loading.value = false
      }
    }
  })
}

function togglePassword() {
  showPassword.value = !showPassword.value
}
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-primary-500 via-primary-600 to-primary-700 flex items-center justify-center p-4">
    <div class="absolute inset-0 overflow-hidden">
      <div class="absolute -top-40 -right-40 w-80 h-80 bg-white/10 rounded-full blur-3xl"></div>
      <div class="absolute -bottom-40 -left-40 w-96 h-96 bg-white/10 rounded-full blur-3xl"></div>
    </div>

    <div class="relative w-full max-w-md">
      <div class="bg-white/95 backdrop-blur-sm rounded-2xl shadow-2xl p-8">
        <div class="text-center mb-8">
          <div class="w-16 h-16 bg-primary-500 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg">
            <Cpu class="w-10 h-10 text-white" />
          </div>
          <h1 class="text-2xl font-bold text-gray-800 mb-2">工业物联网预测性维护系统</h1>
          <p class="text-gray-500">请登录您的账户</p>
        </div>

        <el-form
          ref="formRef"
          :model="loginForm"
          :rules="rules"
          label-position="top"
          @keyup.enter="handleLogin"
        >
          <el-form-item label="用户名" prop="username">
            <el-input
              v-model="loginForm.username"
              placeholder="请输入用户名"
              size="large"
              :prefix-icon="User"
            />
          </el-form-item>

          <el-form-item label="密码" prop="password">
            <el-input
              v-model="loginForm.password"
              :type="showPassword ? 'text' : 'password'"
              placeholder="请输入密码"
              size="large"
              :prefix-icon="Lock"
            >
              <template #suffix>
                <button type="button" @click="togglePassword" class="p-1 hover:bg-gray-100 rounded">
                  <Eye v-if="!showPassword" class="w-5 h-5 text-gray-400" />
                  <EyeOff v-else class="w-5 h-5 text-gray-400" />
                </button>
              </template>
            </el-input>
          </el-form-item>

          <div class="flex items-center justify-between mb-6">
            <el-checkbox v-model="loginForm.remember">记住我</el-checkbox>
            <a href="#" class="text-primary-500 hover:text-primary-600 text-sm">忘记密码？</a>
          </div>

          <el-button
            type="primary"
            size="large"
            class="w-full h-12 text-base font-medium"
            :loading="loading"
            @click="handleLogin"
          >
            {{ loading ? '登录中...' : '登 录' }}
          </el-button>
        </el-form>

        <div class="mt-6 pt-6 border-t border-gray-100">
          <p class="text-center text-sm text-gray-500">
            测试账号：admin / admin123
          </p>
        </div>
      </div>

      <p class="text-center text-white/60 text-sm mt-6">
        © 2024 工业物联网设备预测性维护系统 v1.0
      </p>
    </div>
  </div>
</template>

<style scoped>
:deep(.el-input__wrapper) {
  padding: 0 16px;
}

:deep(.el-input__prefix-inner) {
  margin-right: 8px;
}
</style>
