// Project53/frontend/src/components/Layout.svelte
<script>
    import { Link } from 'svelte-routing';

    let currentPath = typeof window !== 'undefined' ? window.location.pathname : '/';

    function updatePath() {
        currentPath = window.location.pathname;
    }

    const menuItems = [
        { path: '/', label: '实时统计', icon: '📊' },
        { path: '/equipment', label: '设备管理', icon: '⚙️' },
        { path: '/energy-data', label: '能耗数据', icon: '📈' },
        { path: '/saving-plans', label: '节能方案', icon: '💡' },
        { path: '/loss-analysis', label: '损耗分析', icon: '🔍' }
    ];
</script>

<div class="app-container">
    <aside class="sidebar">
        <div class="logo">
            <h1>⚡ 能耗管控系统</h1>
        </div>
        <nav class="menu">
            {#each menuItems as item}
                <Link to={item.path} class={currentPath === item.path ? 'menu-item active' : 'menu-item'}>
                    <span class="icon">{item.icon}</span>
                    <span class="label">{item.label}</span>
                </Link>
            {/each}
        </nav>
    </aside>

    <main class="main-content">
        <slot />
    </main>
</div>

<style>
    .app-container {
        display: flex;
        min-height: 100vh;
    }

    .sidebar {
        width: 220px;
        background: linear-gradient(180deg, #1e3a5f 0%, #0d1b2a 100%);
        color: white;
        padding: 20px 0;
        position: fixed;
        height: 100vh;
        box-shadow: 2px 0 10px rgba(0, 0, 0, 0.1);
    }

    .logo {
        padding: 0 20px 30px;
        border-bottom: 1px solid rgba(255, 255, 255, 0.1);
        margin-bottom: 20px;
    }

    .logo h1 {
        font-size: 18px;
        font-weight: 600;
        margin: 0;
    }

    .menu {
        display: flex;
        flex-direction: column;
    }

    .menu-item {
        display: flex;
        align-items: center;
        padding: 12px 20px;
        color: rgba(255, 255, 255, 0.7);
        text-decoration: none;
        transition: all 0.3s;
        border-left: 3px solid transparent;
    }

    .menu-item:hover {
        background: rgba(255, 255, 255, 0.1);
        color: white;
    }

    .menu-item.active {
        background: rgba(255, 255, 255, 0.15);
        color: white;
        border-left-color: #4ecdc4;
    }

    .icon {
        font-size: 18px;
        margin-right: 12px;
    }

    .label {
        font-size: 14px;
    }

    .main-content {
        flex: 1;
        margin-left: 220px;
        padding: 30px;
        background: #f5f7fa;
        min-height: 100vh;
    }
</style>

// Project1/client/src/views/Layout.vue
<template>
  <div class="app-layout">
    <el-container>
      <el-header class="app-header">
        <div class="header-left">
          <el-icon :size="32" color="#fff"><Key /></el-icon>
          <h1>城市便民开锁服务登记系统</h1>
        </div>
        <div class="header-right">
          <el-menu
            :default-active="activeMenu"
            mode="horizontal"
            background-color="transparent"
            text-color="#fff"
            active-text-color="#ffd04b"
            router
          >
            <el-menu-item index="/dashboard">数据概览</el-menu-item>
            <el-menu-item index="/orders">订单列表</el-menu-item>
            <el-menu-item index="/orders/new">新增订单</el-menu-item>
            <el-menu-item index="/reviews">服务评价</el-menu-item>
          </el-menu>
        </div>
      </el-header>
      <el-main class="app-main">
        <router-view />
      </el-main>
    </el-container>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const activeMenu = computed(() => {
  if (route.path.startsWith('/orders/new')) return '/orders/new'
  if (route.path.startsWith('/orders')) return '/orders'
  return route.path
})
</script>

<style scoped>
.app-layout {
  min-height: 100vh;
}

.app-header {
  background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 30px;
  height: 64px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 12px;
}

.header-left h1 {
  color: white;
  font-size: 20px;
  font-weight: 600;
}

.header-right {
  margin-top: 4px;
}

.app-main {
  padding: 20px;
  background: #f5f7fa;
  min-height: calc(100vh - 64px);
}

:deep(.el-menu) {
  border-bottom: none;
}

:deep(.el-menu--horizontal) {
  height: 40px;
  line-height: 40px;
}
</style>
