// Project48/frontend/src/components/StatCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { TrendingUp, TrendingDown, Minus } from 'lucide-vue-next'

interface Props {
  title: string
  value: string | number
  icon: unknown
  color?: 'primary' | 'success' | 'warning' | 'danger'
  trend?: number
  suffix?: string
}

const props = withDefaults(defineProps<Props>(), {
  color: 'primary',
  suffix: ''
})

const colorClasses = computed(() => {
  const colorMap = {
    primary: {
      bg: 'bg-primary-50',
      icon: 'bg-primary-500',
      text: 'text-primary-600'
    },
    success: {
      bg: 'bg-success-50',
      icon: 'bg-success-500',
      text: 'text-success-600'
    },
    warning: {
      bg: 'bg-warning-50',
      icon: 'bg-warning-500',
      text: 'text-warning-600'
    },
    danger: {
      bg: 'bg-danger-50',
      icon: 'bg-danger-500',
      text: 'text-danger-600'
    }
  }
  return colorMap[props.color]
})

const trendIcon = computed(() => {
  if (!props.trend) return Minus
  return props.trend > 0 ? TrendingUp : TrendingDown
})

const trendColor = computed(() => {
  if (!props.trend) return 'text-gray-500'
  return props.trend > 0 ? 'text-success-500' : 'text-danger-500'
})
</script>

<template>
  <div class="bg-white rounded-xl p-6 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
    <div class="flex items-start justify-between">
      <div class="flex-1">
        <p class="text-sm text-gray-500 mb-2">{{ title }}</p>
        <div class="flex items-baseline gap-1">
          <span class="text-3xl font-bold text-gray-800">{{ value }}</span>
          <span class="text-sm text-gray-500">{{ suffix }}</span>
        </div>
        <div v-if="trend !== undefined" class="flex items-center gap-1 mt-3">
          <component :is="trendIcon" class="w-4 h-4" :class="trendColor" />
          <span class="text-sm" :class="trendColor">
            {{ trend > 0 ? '+' : '' }}{{ trend.toFixed(1) }}%
          </span>
          <span class="text-sm text-gray-400">较上周</span>
        </div>
      </div>
      <div
        class="w-14 h-14 rounded-xl flex items-center justify-center"
        :class="colorClasses.icon"
      >
        <component :is="icon" class="w-7 h-7 text-white" />
      </div>
    </div>
  </div>
</template>

// Project44/frontend/src/components/StatCard.tsx
import { LucideIcon } from 'lucide-react';
import { cn } from '../lib/utils';

interface StatCardProps {
  title: string;
  value: string | number;
  icon: LucideIcon;
  trend?: number;
  color?: 'cyan' | 'emerald' | 'amber' | 'purple' | 'red';
  delay?: number;
}

export function StatCard({
  title,
  value,
  icon: Icon,
  trend,
  color = 'cyan',
  delay = 0,
}: StatCardProps) {
  const colorClasses = {
    cyan: 'from-cyan-500/20 to-cyan-500/5 border-cyan-500/30',
    emerald: 'from-emerald-500/20 to-emerald-500/5 border-emerald-500/30',
    amber: 'from-amber-500/20 to-amber-500/5 border-amber-500/30',
    purple: 'from-purple-500/20 to-purple-500/5 border-purple-500/30',
    red: 'from-red-500/20 to-red-500/5 border-red-500/30',
  };

  const iconColorClasses = {
    cyan: 'text-cyan-400 bg-cyan-500/10',
    emerald: 'text-emerald-400 bg-emerald-500/10',
    amber: 'text-amber-400 bg-amber-500/10',
    purple: 'text-purple-400 bg-purple-500/10',
    red: 'text-red-400 bg-red-500/10',
  };

  return (
    <div
      className={cn(
        'rounded-xl border bg-gradient-to-br p-6 transition-all duration-300 hover:scale-[1.02] animate-slide-in',
        colorClasses[color]
      )}
      style={{ animationDelay: `${delay}ms` }}
    >
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <p className="text-sm text-slate-400 font-medium">{title}</p>
          <p className="mt-2 text-3xl font-bold text-white font-mono number-change">
            {typeof value === 'number' ? value.toLocaleString() : value}
          </p>
          {trend !== undefined && (
            <p
              className={cn(
                'mt-1 text-sm font-medium',
                trend >= 0 ? 'text-emerald-400' : 'text-red-400'
              )}
            >
              {trend >= 0 ? '↑' : '↓'} {Math.abs(trend).toFixed(1)}%
            </p>
          )}
        </div>
        <div
          className={cn(
            'p-3 rounded-xl transition-transform duration-300 group-hover:scale-110',
            iconColorClasses[color]
          )}
        >
          <Icon className="w-6 h-6" />
        </div>
      </div>
    </div>
  );
}
