// Project53/frontend/src/App.svelte
<script>
    import { Router, Route } from 'svelte-routing';
    import Layout from './components/Layout.svelte';
    import Dashboard from './pages/Dashboard.svelte';
    import Equipment from './pages/Equipment.svelte';
    import EnergyData from './pages/EnergyData.svelte';
    import SavingPlans from './pages/SavingPlans.svelte';
    import LossAnalysis from './pages/LossAnalysis.svelte';
</script>

<Router>
    <Layout>
        <Route path="/" component={Dashboard} />
        <Route path="/equipment" component={Equipment} />
        <Route path="/energy-data" component={EnergyData} />
        <Route path="/saving-plans" component={SavingPlans} />
        <Route path="/loss-analysis" component={LossAnalysis} />
    </Layout>
</Router>

// Project44/frontend/src/App.tsx
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Layout from './components/Layout';
import Dashboard from './pages/Dashboard';
import DataQuery from './pages/DataQuery';
import SystemStatus from './pages/SystemStatus';

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Layout />}>
          <Route index element={<Dashboard />} />
          <Route path="data" element={<DataQuery />} />
          <Route path="system" element={<SystemStatus />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}
