// Project18/frontend/src/components/Devices.jsx
import { createSignal, onMount, Show, For } from 'solid-js';

export default function Devices(props) {
  const [devices, setDevices] = createSignal([]);
  const [productLines, setProductLines] = createSignal([]);
  const [showModal, setShowModal] = createSignal(false);
  const [editingDevice, setEditingDevice] = createSignal(null);
  const [formData, setFormData] = createSignal({
    name: '',
    ip_address: '',
    product_line: '',
    status: 'offline',
  });

  const fetchData = async () => {
    try {
      const [devicesRes, linesRes] = await Promise.all([
        fetch(`${props.apiBase}/devices`),
        fetch(`${props.apiBase}/product-lines`),
      ]);
      const devicesData = await devicesRes.json();
      const linesData = await linesRes.json();

      if (devicesData.success) {
        setDevices(devicesData.data);
      }
      if (linesData.success) {
        setProductLines(linesData.data);
      }
    } catch (err) {
      console.error('Failed to fetch data:', err);
    }
  };

  onMount(() => {
    fetchData();
  });

  const openCreateModal = () => {
    setEditingDevice(null);
    setFormData({ name: '', ip_address: '', product_line: '', status: 'offline' });
    setShowModal(true);
  };

  const openEditModal = (device) => {
    setEditingDevice(device);
    setFormData({
      name: device.name,
      ip_address: device.ip_address,
      product_line: device.product_line || '',
      status: device.status,
    });
    setShowModal(true);
  };

  const handleSubmit = async () => {
    if (!formData().name.trim()) {
      alert('请输入设备名称');
      return;
    }

    try {
      let res;
      if (editingDevice()) {
        res = await fetch(`${props.apiBase}/devices/${editingDevice().id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(formData()),
        });
      } else {
        res = await fetch(`${props.apiBase}/devices`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(formData()),
        });
      }

      const data = await res.json();
      if (data.success) {
        setShowModal(false);
        fetchData();
      } else {
        alert(data.error || '操作失败');
      }
    } catch (err) {
      alert('请求失败: ' + err.message);
    }
  };

  const handleDelete = async (id) => {
    if (!confirm('确定要删除此设备吗？')) return;

    try {
      const res = await fetch(`${props.apiBase}/devices/${id}`, {
        method: 'DELETE',
      });
      const data = await res.json();
      if (data.success) {
        fetchData();
      } else {
        alert(data.error || '删除失败');
      }
    } catch (err) {
      alert('删除失败: ' + err.message);
    }
  };

  const formatTime = (time) => {
    if (!time) return '-';
    const date = new Date(time);
    return date.toLocaleString('zh-CN');
  };

  const getLineName = (lineId) => {
    const line = productLines().find((l) => l.id === lineId);
    return line ? line.name : '-';
  };

  return (
    <div>
      <div class="page-header">
        <h2>设备管理</h2>
        <p>管理边缘计算设备和网关</p>
      </div>

      <div class="card">
        <div class="card-header">
          <h3>设备列表</h3>
          <button class="btn btn-primary" onClick={openCreateModal}>
            + 新增设备
          </button>
        </div>

        {devices().length > 0 ? (
          <table>
            <thead>
              <tr>
                <th>设备名称</th>
                <th>IP地址</th>
                <th>所属产线</th>
                <th>状态</th>
                <th>CPU使用率</th>
                <th>内存使用率</th>
                <th>最后在线</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              <For each={devices()}>
                {(device) => (
                  <tr>
                    <td><strong>{device.name}</strong></td>
                    <td>{device.ip_address}</td>
                    <td>{getLineName(device.product_line)}</td>
                    <td>
                      <span class={`status-badge status-${device.status}`}>
                        {device.status === 'online' ? '在线' : '离线'}
                      </span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', 'align-items': 'center', gap: '8px' }}>
                        <div class="progress-bar" style={{ width: '80px' }}>
                          <div class="progress-fill cpu" style={{ width: `${device.cpu_usage}%` }}></div>
                        </div>
                        <span style={{ 'font-size': '12px' }}>{device.cpu_usage.toFixed(1)}%</span>
                      </div>
                    </td>
                    <td>
                      <div style={{ display: 'flex', 'align-items': 'center', gap: '8px' }}>
                        <div class="progress-bar" style={{ width: '80px' }}>
                          <div class="progress-fill memory" style={{ width: `${device.memory_usage}%` }}></div>
                        </div>
                        <span style={{ 'font-size': '12px' }}>{device.memory_usage.toFixed(1)}%</span>
                      </div>
                    </td>
                    <td>{formatTime(device.last_seen)}</td>
                    <td>
                      <div class="actions-cell">
                        <button class="btn btn-outline btn-sm" onClick={() => openEditModal(device)}>
                          编辑
                        </button>
                        <button class="btn btn-danger btn-sm" onClick={() => handleDelete(device.id)}>
                          删除
                        </button>
                      </div>
                    </td>
                  </tr>
                )}
              </For>
            </tbody>
          </table>
        ) : (
          <div class="empty-state">
            <div class="empty-state-icon">⚙️</div>
            <p>暂无设备数据</p>
          </div>
        )}
      </div>

      <Show when={showModal()}>
        <div class="modal-overlay" onClick={() => setShowModal(false)}>
          <div class="modal" onClick={(e) => e.stopPropagation()}>
            <div class="modal-header">
              <h3>{editingDevice() ? '编辑设备' : '新增设备'}</h3>
              <button class="modal-close" onClick={() => setShowModal(false)}>&times;</button>
            </div>
            <div class="form-group">
              <label>设备名称 *</label>
              <input
                type="text"
                value={formData().name}
                onInput={(e) => setFormData({ ...formData(), name: e.target.value })}
                placeholder="请输入设备名称"
              />
            </div>
            <div class="form-group">
              <label>IP地址</label>
              <input
                type="text"
                value={formData().ip_address}
                onInput={(e) => setFormData({ ...formData(), ip_address: e.target.value })}
                placeholder="192.168.1.100"
              />
            </div>
            <div class="form-group">
              <label>所属产线</label>
              <select
                value={formData().product_line}
                onChange={(e) => setFormData({ ...formData(), product_line: e.target.value })}
              >
                <option value="">无</option>
                <For each={productLines()}>
                  {(line) => (
                    <option value={line.id}>{line.name}</option>
                  )}
                </For>
              </select>
            </div>
            <div class="form-group">
              <label>状态</label>
              <select
                value={formData().status}
                onChange={(e) => setFormData({ ...formData(), status: e.target.value })}
              >
                <option value="online">在线</option>
                <option value="offline">离线</option>
              </select>
            </div>
            <div class="form-actions">
              <button class="btn btn-outline" onClick={() => setShowModal(false)}>取消</button>
              <button class="btn btn-primary" onClick={handleSubmit}>
                {editingDevice() ? '保存' : '创建'}
              </button>
            </div>
          </div>
        </div>
      </Show>
    </div>
  );
}

// Project15/frontend/src/pages/Devices.svelte
<script>
  import { onMount } from 'svelte';
  import { devicesList, elderlyList } from '../store.js';

  let loading = true;
  let showModal = false;
  let editingDevice = null;
  let formData = {
    deviceCode: '',
    deviceType: '',
    deviceName: '',
    bluetoothMac: '',
    elderlyId: ''
  };

  async function fetchData() {
    loading = true;
    try {
      const [devicesRes, elderlyRes] = await Promise.all([
        fetch('/api/devices').then(r => r.json()),
        fetch('/api/elderly').then(r => r.json())
      ]);
      devicesList.set(devicesRes.data || []);
      elderlyList.set(elderlyRes.data || []);
    } catch (error) {
      console.error('Failed to fetch data:', error);
    } finally {
      loading = false;
    }
  }

  function handleAdd() {
    editingDevice = null;
    formData = {
      deviceCode: '',
      deviceType: '',
      deviceName: '',
      bluetoothMac: '',
      elderlyId: ''
    };
    showModal = true;
  }

  function handleEdit(device) {
    editingDevice = device;
    formData = { ...device };
    showModal = true;
  }

  async function handleDelete(id) {
    if (!confirm('确定要删除该设备吗？')) return;
    try {
      await fetch(`/api/devices/${id}`, { method: 'DELETE' });
      fetchData();
    } catch (error) {
      console.error('Failed to delete device:', error);
    }
  }

  async function handleSubmit() {
    try {
      const url = editingDevice ? `/api/devices/${editingDevice.id}` : '/api/devices';
      const method = editingDevice ? 'PUT' : 'POST';
      
      await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData)
      });
      
      showModal = false;
      fetchData();
    } catch (error) {
      console.error('Failed to save device:', error);
    }
  }

  function getConnectionStatusClass(status) {
    switch (status) {
      case 'CONNECTED': return 'tag-success';
      case 'DISCONNECTED': return 'tag-danger';
      default: return 'tag-warning';
    }
  }

  function getConnectionStatusText(status) {
    switch (status) {
      case 'CONNECTED': return '已连接';
      case 'DISCONNECTED': return '已断开';
      default: return '未知';
    }
  }

  function getElderlyName(elderlyId) {
    const elderly = $elderlyList.find(e => e.id === elderlyId);
    return elderly ? elderly.name : '未绑定';
  }

  onMount(fetchData);
</script>

<div class="devices-page">
  <div class="page-header">
    <h2>设备管理</h2>
    <button class="btn btn-primary" on:click={handleAdd}>
      <span>+ 添加设备</span>
    </button>
  </div>

  {#if loading}
    <div class="loading">
      <div class="spinner"></div>
      <span>加载中...</span>
    </div>
  {:else if $devicesList.length > 0}
    <div class="devices-grid">
      {#each $devicesList as device (device.id)}
        <div class="device-card">
          <div class="device-header">
            <div class="device-icon">📱</div>
            <div class="device-info">
              <h3>{device.deviceName || device.deviceCode}</h3>
              <p>{device.deviceType}</p>
            </div>
            <span class="tag {getConnectionStatusClass(device.connectionStatus)}">
              {getConnectionStatusText(device.connectionStatus)}
            </span>
          </div>
          <div class="device-details">
            <div class="detail-row">
              <span class="label">设备编号：</span>
              <span class="value">{device.deviceCode}</span>
            </div>
            <div class="detail-row">
              <span class="label">蓝牙地址：</span>
              <span class="value">{device.bluetoothMac}</span>
            </div>
            <div class="detail-row">
              <span class="label">绑定老人：</span>
              <span class="value">{getElderlyName(device.elderlyId)}</span>
            </div>
            <div class="detail-row">
              <span class="label">电池电量：</span>
              <div class="battery-indicator">
                <div class="battery-bar">
                  <div 
                    class="battery-level" 
                    style="width: {device.batteryLevel || 0}%"
                  ></div>
                </div>
                <span>{device.batteryLevel || 0}%</span>
              </div>
            </div>
            {#if device.lastHeartbeatTime}
              <div class="detail-row">
                <span class="label">最后心跳：</span>
                <span class="value">{device.lastHeartbeatTime}</span>
              </div>
            {/if}
          </div>
          <div class="device-actions">
            <button class="btn btn-sm" on:click={() => handleEdit(device)}>编辑</button>
            <button class="btn btn-sm btn-danger" on:click={() => handleDelete(device.id)}>删除</button>
          </div>
        </div>
      {/each}
    </div>
  {:else}
    <div class="empty-state">
      <div class="empty-icon">📱</div>
      <p>暂无设备信息</p>
    </div>
  {/if}
</div>

{#if showModal}
  <div class="modal-overlay" on:click={() => showModal = false}>
    <div class="modal-content" on:click|stopPropagation>
      <div class="modal-header">
        <h2>{editingDevice ? '编辑设备' : '添加设备'}</h2>
        <button class="modal-close" on:click={() => showModal = false}>×</button>
      </div>
      <form on:submit|preventDefault={handleSubmit}>
        <div class="form-group">
          <label>设备编号 *</label>
          <input type="text" bind:value={formData.deviceCode} required placeholder="请输入设备编号">
        </div>
        <div class="form-group">
          <label>设备类型</label>
          <select bind:value={formData.deviceType}>
            <option value="">请选择</option>
            <option value="智能手表">智能手表</option>
            <option value="智能手环">智能手环</option>
            <option value="智能项链">智能项链</option>
            <option value="其他">其他</option>
          </select>
        </div>
        <div class="form-group">
          <label>设备名称</label>
          <input type="text" bind:value={formData.deviceName} placeholder="请输入设备名称">
        </div>
        <div class="form-group">
          <label>蓝牙MAC地址</label>
          <input type="text" bind:value={formData.bluetoothMac} placeholder="例如：00:1A:2B:3C:4D:5E">
        </div>
        <div class="form-group">
          <label>绑定老人</label>
          <select bind:value={formData.elderlyId}>
            <option value="">请选择</option>
            {#each $elderlyList as elderly (elderly.id)}
              <option value={elderly.id}>{elderly.name}</option>
            {/each}
          </select>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn" on:click={() => showModal = false}>取消</button>
          <button type="submit" class="btn btn-primary">保存</button>
        </div>
      </form>
    </div>
  </div>
{/if}

<style>
  .devices-page {
    display: flex;
    flex-direction: column;
    gap: 20px;
  }

  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .page-header h2 {
    font-size: 20px;
    color: #262626;
    margin: 0;
  }

  .devices-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
    gap: 20px;
  }

  .device-card {
    background: #fff;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    overflow: hidden;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
  }

  .device-card:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
  }

  .device-header {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 16px;
    background: linear-gradient(135deg, #f0f5ff 0%, #e6f7ff 100%);
    border-bottom: 1px solid #f0f0f0;
  }

  .device-icon {
    font-size: 32px;
  }

  .device-info h3 {
    font-size: 16px;
    color: #262626;
    margin: 0 0 4px 0;
  }

  .device-info p {
    font-size: 12px;
    color: #8c8c8c;
    margin: 0;
  }

  .device-details {
    padding: 16px;
  }

  .detail-row {
    display: flex;
    align-items: center;
    margin-bottom: 8px;
    font-size: 13px;
  }

  .detail-row .label {
    color: #595959;
    min-width: 80px;
  }

  .detail-row .value {
    color: #262626;
    flex: 1;
  }

  .battery-indicator {
    display: flex;
    align-items: center;
    gap: 8px;
    flex: 1;
  }

  .battery-bar {
    width: 100px;
    height: 12px;
    background: #f0f0f0;
    border-radius: 6px;
    overflow: hidden;
  }

  .battery-level {
    height: 100%;
    background: linear-gradient(90deg, #52c41a 0%, #73d13d 100%);
    transition: width 0.3s ease;
  }

  .device-actions {
    display: flex;
    gap: 8px;
    padding: 12px 16px;
    border-top: 1px solid #f0f0f0;
    background: #fafafa;
  }

  .btn-sm {
    padding: 4px 12px;
    font-size: 12px;
  }

  .modal-footer {
    display: flex;
    justify-content: flex-end;
    gap: 12px;
    margin-top: 20px;
    padding-top: 16px;
    border-top: 1px solid #f0f0f0;
  }
</style>
