// Project42/src/App.tsx
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import Layout from "@/components/Layout";
import Dashboard from "@/pages/Dashboard";
import Materials from "@/pages/Materials";
import Checkin from "@/pages/Checkin";
import Progress from "@/pages/Progress";

export default function App() {
  return (
    <Router>
      <Routes>
        <Route element={<Layout />}>
          <Route path="/" element={<Dashboard />} />
          <Route path="/materials" element={<Materials />} />
          <Route path="/checkin" element={<Checkin />} />
          <Route path="/progress" element={<Progress />} />
        </Route>
      </Routes>
    </Router>
  );
}

// Project53/frontend/src/App.svelte
<script>
    import { Router, Route } from 'svelte-routing';
    import Layout from './components/Layout.svelte';
    import Dashboard from './pages/Dashboard.svelte';
    import Equipment from './pages/Equipment.svelte';
    import EnergyData from './pages/EnergyData.svelte';
    import SavingPlans from './pages/SavingPlans.svelte';
    import LossAnalysis from './pages/LossAnalysis.svelte';
</script>

<Router>
    <Layout>
        <Route path="/" component={Dashboard} />
        <Route path="/equipment" component={Equipment} />
        <Route path="/energy-data" component={EnergyData} />
        <Route path="/saving-plans" component={SavingPlans} />
        <Route path="/loss-analysis" component={LossAnalysis} />
    </Layout>
</Router>
